services:
  neo4j:
    image: neo4j:5
    container_name: graph-guided-datasheet-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
volumes:
  neo4j_data:
  neo4j_logs:
# 这一步完成后，你至少能打开：
# http://localhost:7474

# docker compose up -d